/*
 * VistaDialog.java
 *
 * Created on 9 de junio de 2006, 19:33
 */

package Vistas;

import Modelo.Modelo;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author  root
 */
public class VistaDialog extends javax.swing.JDialog implements Observer 
{
    Modelo modeloObservado;
    
    /** Creates new form VistaDialog */
    public VistaDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        stTexto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(stTexto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 271, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(stTexto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VistaDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField stTexto;
    // End of variables declaration//GEN-END:variables
    
    public void setTexto(String t)
    {
        stTexto.setText("");
        stTexto.setText(t);
    }
    
    public void setModelo(Modelo modelo)
    {
        this.modeloObservado = modelo;  
        modeloObservado.addObserver(this);
    }

    public void update(Observable observable, Object object)
    {
        if(observable != modeloObservado)
            throw new IllegalArgumentException();
        String dato = (String)object;
        setTexto(dato);
    }
}
