/*
 * ModeloControlador.java
 *
 * Created on 9 de junio de 2006, 18:41
 */

package Modelo;

import Vistas.VistaA;
import Vistas.VistaDialog;
import java.awt.Dimension;
import java.awt.Rectangle;

/**
 *
 * @author  root
 */
public class ModeloControlador extends javax.swing.JFrame
{
    Modelo modelo;
    VistaA vista;
    VistaDialog vistaDialog;
    
    /** Creates new form ModeloControlador */
    public ModeloControlador()
    {
          initComponents();
        modelo = new Modelo();
        vista = new VistaA(modelo);
        vista.setVisible(true);
        vista.setEnabled(true);
        vista.setBounds(getRec());
        desktopPane.add(vista); 
        vistaDialog = new VistaDialog(this,false);
        vistaDialog.setVisible(true);
        vistaDialog.setModelo(modelo);
         //initComponents();
    }
    
     public Rectangle getRec()
    {
        Dimension dim = desktopPane.getSize();
        Rectangle rec = new Rectangle();
        rec.setSize(dim);
        return rec;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        desktopPane = new javax.swing.JDesktopPane();
        stTexto = new javax.swing.JTextField();
        botonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonOK.setText("OK");
        botonOK.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botonOKActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(desktopPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 537, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(stTexto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 315, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(27, 27, 27)
                        .add(botonOK)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(77, 77, 77)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(stTexto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(botonOK))
                .add(27, 27, 27)
                .add(desktopPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonOKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botonOKActionPerformed
    {//GEN-HEADEREND:event_botonOKActionPerformed
        modelo.setDato(stTexto.getText().trim());
    }//GEN-LAST:event_botonOKActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ModeloControlador().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonOK;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JTextField stTexto;
    // End of variables declaration//GEN-END:variables
    
}
